FROM ubuntu:22.04

RUN apt-get update &&     apt-get install -y python3 python3-pip git

RUN git clone --depth 1 --single-branch --branch main https://github.com/gabrielpirovanemiguel/Tokaki.git /app

WORKDIR /app

RUN pip3 install -r requirements.txt

EXPOSE 8080

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:app"]
