services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: app
    expose:
      - "8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
