services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: app
    expose:
      - "8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: nginx
    ports:
      - "8000:8000"
    depends_on:
      - app
